---
- name: Configure file hosts
  hosts: "{{ target }}"
  gather_facts: true
  become: true
  vars:
    target: all
  tasks:
    - name: "Modify /etc/hosts"
      ansible.builtin.lineinfile:
        line: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_fqdn'] }}"
        dest: /etc/hosts
      loop: "{{ groups[target] }}"
